#!/usr/bin/env perl

use strict; use warnings; use warnings FATAL => 'uninitialized';

use Test::Harness;

# make sure not to carry over a TEST=0 setting, which would make
# Chj::TEST based testing fail
$ENV{TEST}=1;

our @t=
  qw(
	require_and_run_tests
	testlazy
	testlazy10
	functional_XML-test
	functional_XML-t-div
	csv2xml
	htmlgen
	intro-basics
	trampoline-fix
	examples-fibs
	examples-primes
	predicates
	skip-internal
	skip
	skip-leak
	csvstreams
	perl-weaken-coderef
	perl-goto-leak
   );

runtests(map {"t/$_"} @t);
