#!/usr/bin/perl -w

use strict; use warnings FATAL => 'uninitialized';

use Test::Harness;

our @t=
  qw(
	require_and_run_tests
	testlazy
	testlazy10
	ftemplate-test
	csv2xml
	intro-basics
	csvstreams
   );

runtests(map {"t/$_"} @t);
