#!/usr/bin/perl -w

use strict; use warnings FATAL => 'uninitialized';

use Test::Harness;

our @t=
  qw(
	t1-require
	t2-testlazy
	t2-testlazy10
	t3-ftemplate-test
	t4-csv2xml
   );

runtests(map {"t/$_"} @t);
