#!/usr/bin/env perl

# Wed Jun 18 03:48:27 BST 2014
(my $email='ch%christianjaeger,ch')=~ tr/%,/@./;

use strict; use warnings; use warnings FATAL => 'uninitialized';

our ($mydir, $myname);
BEGIN {
    $0=~ /(.*?)([^\/]+)\z/s or die "?";
    ($mydir, $myname)=($1,$2);
}
use lib "$mydir/../../lib";

use PXML::XHTML ":all";
use PXML::Serialize "pxml_print_fragment_fast";
use FP::Lazy;
use FP::List;
use FP::Stream;
use Chj::TEST ":all";
use Chj::Backtrace;
use Chj::repl;


TEST_STDOUT { pxml_print_fragment_fast ( A({href=>"hah"}, "Hello ", I("World", B("!"))), *STDOUT{IO} ) }
  '<a href="hah">Hello <i>World<b>!</b></i></a>';

TEST {  A({href=>"hah"}, "Hello ", I("World", undef, B("!")), cons(" ", string2stream("You're great.")))->text }
  'Hello World! You\'re great.';


perhaps_run_tests(__PACKAGE__) or repl;

