#!/usr/bin/env perl

# Copyright (c) 2015 Christian Jaeger, copying@christianjaeger.ch
# This is free software. See the file COPYING.md that came bundled
# with this file.

use strict; use warnings; use warnings FATAL => 'uninitialized';

# avoid dependency on Sub::Call::Tail:
use lib "./lib";
use Chj::xopen 'xopen_read';
use Chj::xperlfunc qw(dirname xxsystem);
mkdir ".htmlgen";
my $manif= xopen_read "MANIFEST";
local $_;
while (<$manif>) {
    chomp;
    next unless m|^htmlgen/|;
    my $path= $_;
    mkdir ".".dirname $path;
    xxsystem ("bin/expand-tail", $path, ".".$path);
}
$manif->xclose;
