#!/usr/bin/env perl

use strict; use warnings; use warnings FATAL => 'uninitialized';

our $len= 210;
require "meta/test.pl";

use Test::Requires qw(Text::CSV);
use Test::More;

is readin ("examples/csv_to_xml examples/csv_to_xml-example.csv|"),
   readin ("< t/csv_to_xml.expected");

done_testing;
