#!/usr/bin/env perl

use strict; use warnings; use warnings FATAL => 'uninitialized';

our %deps;
BEGIN {
    %deps= map {$_=>1} qw(Method::Signatures Text::CSV);
    for (keys %deps) {
	eval "require $_; 1" and delete $deps{$_}
    }
}

use Test::More %deps ?
  (skip_all=> "failed to use ".join ", ", keys %deps):
  (tests=> 2);

require "./testmem.pl";
setlimit_mem_MB (80); # 14 is enough on 32bit Debian, 64bit will need more

is system ("examples/gen-csv t/test-a.csv 40000"), 0;
# 20000 pass on 32bit Debian even with bug

is system ("examples/csv2xml t/test-a.csv -o t/test-a.xml"), 0;

