#!/usr/bin/perl -w

use strict; use warnings FATAL => 'uninitialized';

our $deps_ok; BEGIN { $deps_ok= eval { require Method::Signatures; 1 } };

use Test::More $deps_ok ? (tests=> 2) : (skip_all=> "don't have Method::Signatures");

require "./testmem.pl";
setlimit_mem_MB (80); # 14 is enough on 32bit Debian, 64bit will need more

is system ("examples/gen-csv t/test-a.csv 40000"), 0;
# 20000 pass on 32bit Debian even with bug

is system ("examples/csv2xml t/test-a.csv -o t/test-a.xml"), 0;

