#!/usr/bin/env perl

# Copyright (c) 2019 Christian Jaeger, copying@christianjaeger.ch
# This is free software. See the file COPYING.md that came bundled
# with this file.

use strict; use warnings; use warnings FATAL => 'uninitialized';

use Test::Requires qw(Function::Parameters);
$ENV{RUN_TESTS}=1; exec "examples/sendprepare" or exit 1;
