#!/usr/bin/env perl

# Copyright (c) 2015 Christian Jaeger, copying@christianjaeger.ch
# This is free software. See the file COPYING.md that came bundled
# with this file.

use strict; use warnings; use warnings FATAL => 'uninitialized';

$ENV{RUN_TESTS}=1; exec "functional_XML/t/div" or exit 1;

# XX run functional_XML/t/stream as well? That one is slow, though.
