#!/usr/bin/env perl

use strict; use warnings; use warnings FATAL => 'uninitialized';

our $len= 672;
require "./test.pl";

use Test::More;

system ("functional_XML/test 10001000") == 0
  or die;

is readin ("< out.xhtml"), readin ("< t/functional_XML-test.expected");

done_testing;
