#!/usr/bin/env perl

# Copyright (c) 2015 Christian Jaeger, copying@christianjaeger.ch
# This is free software. See the file COPYING.md that came bundled
# with this file.

use strict; use warnings; use warnings FATAL => 'uninitialized';

our $len= 672;
require "./meta/test.pl";

use Test::More;

system ("functional_XML/test 10001000") == 0
  or die;

is readin ("< out.xhtml"), readin ("< t/functional_XML-test.expected");

done_testing;
