#!/usr/bin/env perl

# Copyright (c) 2015 Christian Jaeger, copying@christianjaeger.ch
# This is free software. See the file COPYING.md that came bundled
# with this file.

use strict; use warnings; use warnings FATAL => 'uninitialized';

use Test::Requires
  +{
    'Function::Parameters'=> 0,
    'Sub::Call::Tail'=> 0,
    'Text::Markdown'=> 0,
    'HTML::TreeBuilder'=> 0,
   };

$ENV{RUN_TESTS}=1; exec "website/gen" or exit 1;
