#!/usr/bin/env perl

use strict; use warnings; use warnings FATAL => 'uninitialized';

require "meta/test.pl";

use Test::More;

require "./testmem.pl";
setlimit_mem_MB (30);

SKIP: {
    skip "Perl issue", 1 unless $ENV{TEST_PERL};

    is readin("t/perl/goto-leak 100000 1 |"),
      "5000050000\n";
}

done_testing;
