#!/usr/bin/env perl

use strict; use warnings; use warnings FATAL => 'uninitialized';

require "./test.pl";

use Test::More;

require "./testmem.pl";
setlimit_mem_MB (40);

is readin("t/perl/weaken-coderef 2 50000 |"),
  "3\n";

done_testing;
