#!/usr/bin/env perl

use strict; use warnings; use warnings FATAL => 'uninitialized';

require "./test.pl";

use Test::More;

require "./testmem.pl";
setlimit_mem_MB (30);

is readin("t/perl/weaken-coderef 2 50000 |"),
  "3\n";

my $n= 30000;
my $res= "450015000\n";

is readin("t/perl/weaken-coderef $n 1 |"),
  $res;

is readin("t/perl/weaken-coderef-alternative-fix Y $n 1 |"),
  $res;

is readin("t/perl/weaken-coderef-alternative-fix rec $n 1 |"),
  $res;

is readin("t/perl/weaken-coderef-alternative-fix '' $n 1 |"),
  $res;

done_testing;
