#!/usr/bin/env perl

# Copyright (c) 2015 Christian Jaeger, copying@christianjaeger.ch
# This is free software. See the file COPYING.md that came bundled
# with this file.

use strict; use warnings; use warnings FATAL => 'uninitialized';

# find modules from functional-perl working directory (not installed)
use Cwd 'abs_path';
our ($mydir, $myname); BEGIN {
    my $location= (-l $0) ? abs_path ($0) : $0;
    $location=~ /(.*?)([^\/]+?)_?\z/s or die "?";
    ($mydir, $myname)=($1,$2);
}
use lib "$mydir/../lib";
use lib "$mydir/../meta";

use ModuleList;

our $modules= modulenamelist;

# ------------------------------------------------------------------
# Non-core dependencies of modules to decide whether to skip testing
# them.  XX: keep these updated!

our %dependencies=
  (
   'FP::Text::CSV'=> [qw(Text::CSV)],
   'FP::url_'=> [qw(URI)],
  );


# ------------------------------------------------------------------


use Test::More;

for (@$modules) {
  SKIP: {
	if (my $ds= $dependencies{$_}) {
	    for my $d (@$ds) {
		eval "require $d; 1" or skip "failed to use $d", 1
	    }
	}
	require_ok $_
    }
}

is( eval { Chj::TEST::run_tests() } // do { diag $@; undef}, 0, "run_tests");

done_testing;


#use Chj::ruse;
use Chj::Backtrace;
#use Chj::repl;
#repl;
