#!/usr/bin/env perl

use strict; use warnings; use warnings FATAL => 'uninitialized';

require "./test.pl";

use Test::More tests=> 1;

require "./testmem.pl";
setlimit_mem_MB (40);

is readin("head -c 200000000 /dev/zero | examples/skip --leaktest 10000000 1 | wc -c |"),
  "189999999\n";

