#!/usr/bin/env perl

use strict; use warnings; use warnings FATAL => 'uninitialized';

require "meta/test.pl";

use Test::More;

require "./testmem.pl";
setlimit_mem_MB (50);

is readin("head -c 200000000 /dev/zero | examples/skip --leaktest 10000000 1 | wc -c |"),
  "189999999\n";

done_testing;
