#!/usr/bin/perl -w

use strict; use warnings FATAL => 'uninitialized';

our $len= 1000;
require "./test.pl";

use Test::More tests=> 1;

is readin ("ftemplate/testlazy|"), readin ("< t/testlazy-expected");

