#!/usr/bin/perl -w

use strict; use warnings FATAL => 'uninitialized';

our $len= 759;
require "./test.pl";

use Test::More tests=> 1;

$ENV{N}= 10;
$ENV{T}= 0;
is readin ("ftemplate/testlazy|"), readin ("< t/t2-testlazy10.expected");

