#!/usr/bin/perl -w

use strict; use warnings FATAL => 'uninitialized';

our $len= 672;
require "./test.pl";

use Test::More tests=> 1;

system ("ftemplate/test 10001000") == 0
  or die;

is readin ("< out.xhtml"), readin ("< t/t3-ftemplate-test.expected");

