#!/usr/bin/env perl

use strict; use warnings; use warnings FATAL => 'uninitialized';

our $len= 759;
require "./test.pl";

use Test::More;

$ENV{N}= 10;
$ENV{T}= 0;
is readin ("functional_XML/testlazy|"), readin ("< t/testlazy10.expected");

done_testing;
