#!/usr/bin/env perl

use strict; use warnings; use warnings FATAL => 'uninitialized';

our $len= 1000;
require "./test.pl";

use Test::More tests=> 1;

use POSIX 'SIGPIPE';
our $sigpipe_is_fine= sub {
    my ($buf, $default_on_error)= @_;
    $? == SIGPIPE ? $buf : &$default_on_error();
};

is readin ("ftemplate/testlazy|", $sigpipe_is_fine), readin ("< t/testlazy.expected");

