#!/usr/bin/env perl

use strict; use warnings; use warnings FATAL => 'uninitialized';

our $len= 672;
require "meta/test.pl";

use Test::More;
use lib "./lib";
use Chj::xperlfunc qw(xprintln);
use Chj::xIO qw(capture_stdout);
use Chj::Backtrace;

# UNIVERSAL::isa does not require a reference
is do { my $v= "IO"; UNIVERSAL::isa($v,"IO") },
  1;

# just to be sure
is capture_stdout { xprintln (" a Foo") },
  " a Foo\n";


# the actual tests

is capture_stdout { xprintln ("IO") },
  "IO\n";

is capture_stdout { xprintln ("IO", "IO") },
  "IOIO\n";



done_testing;
