#!/usr/bin/env perl

# Wed Jun 18 03:48:27 BST 2014
(my $email='ch%christianjaeger,ch')=~ tr/%,/@./;

use strict; use warnings; use warnings FATAL => 'uninitialized';

our ($mydir, $myname);
BEGIN {
    $0=~ /(.*?)([^\/]+)\z/s or die "?";
    ($mydir, $myname)=($1,$2);
}
use lib "$mydir/../../lib";

use Chj::TEST ":all";
use PXML::XHTML ":all";
use PXML::Serialize "pxml_print_fragment_fast";
use FP::Lazy;
use FP::List;
use FP::Stream;
use FP::Array ":all"; # XXX inconsistency in export directives
use FP::PureArray;

TEST_STDOUT { pxml_print_fragment_fast
		( A({href=>"hah"},
		    "Hello ",
		    I("World", B("!"))), *STDOUT{IO} ) }
  '<a href="hah">Hello <i>World<b>!</b></i></a>';

TEST { A({href=>"hah"},
	 "Hello ",
	 I("World", undef, B("!")),
	 cons(" ", string2stream("You're great.")))->text }
  'Hello World! You\'re great.';

TEST { P(list)->string }
  '<p></p>';

TEST { P(list 1, 2, 3)->string }
  '<p>123</p>';

TEST { P(array 1, 2, 3)->string }
  '<p>123</p>';

TEST { P(purearray 1, 2, 3)->string }
  '<p>123</p>';


use Chj::Backtrace;
use Chj::repl;

perhaps_run_tests(__PACKAGE__) or repl;

