#!/bin/bash
set -euo pipefail
# enable job control consistently, not just when there is a tty:
set -m
IFS=

mydir=$(dirname "$0")

set -x

rsync -auvz --delete --exclude .git --exclude lpw-talk --exclude london.pm-talk "$mydir"/www/. servi:www/functional-perl.org/.

